asset_path: /home/june/Research/hcrl_isaac_manager/resources/IsaacLab/source/hcrl_isaaclab/resources/hcrl_robots/spacecraft/spacecraft.urdf
usd_dir: /home/june/Research/hcrl_isaac_manager/resources/IsaacLab/source/hcrl_isaaclab/resources/hcrl_robots/spacecraft/spacecraft_usd
usd_file_name: null
force_usd_conversion: true
make_instanceable: true
fix_base: false
root_link_name: base_link
link_density: 0.0
merge_fixed_joints: false
convert_mimic_joints_to_normal_joints: false
joint_drive:
  drive_type: force
  target_type: none
  gains:
    stiffness: 0.0
    damping: null
collider_type: convex_hull
self_collision: false
replace_cylinders_with_capsules: false
collision_from_visuals: false
func: isaaclab.sim.spawners.from_files.from_files:spawn_from_urdf
visible: true
semantic_tags: null
copy_from_source: true
mass_props: null
deformable_props: null
rigid_props:
  rigid_body_enabled: null
  kinematic_enabled: null
  disable_gravity: true
  linear_damping: 0.0
  angular_damping: 0.0
  max_linear_velocity: 1000.0
  max_angular_velocity: 1000.0
  max_depenetration_velocity: 1.0
  max_contact_impulse: null
  enable_gyroscopic_forces: null
  retain_accelerations: false
  solver_position_iteration_count: null
  solver_velocity_iteration_count: null
  sleep_threshold: null
  stabilization_threshold: null
collision_props: null
activate_contact_sensors: false
scale: null
articulation_props:
  articulation_enabled: null
  enabled_self_collisions: false
  solver_position_iteration_count: 4
  solver_velocity_iteration_count: 0
  sleep_threshold: null
  stabilization_threshold: null
  fix_root_link: null
fixed_tendons_props: null
spatial_tendons_props: null
joint_drive_props: null
visual_material_path: material
visual_material: null
##
# Generated by UrdfConverter on 2025-10-01 at 17:37:50.
##
